services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - wordpress-network
    expose:
      - 3306

  pma:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
    networks:
      - wordpress-network
    ports:
      - 8026:80
    links:
      - db

networks:
  wordpress-network:
    external: true
