version: "3.8"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./mysql-data:/var/lib/mysql
    expose:
      - 3306

  pma:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - 8082:80
    links:
      - db

networks:
  default:
    external:
      name: wordpress-sites
