services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - ./proxy.conf:/etc/nginx/proxy.conf
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wordpress-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     
        max-file: "3"
    networks:
      - wordpress-network

volumes:
  certs:
  html:
  vhostd:
  confd:
  acme:

networks:
  wordpress-network:
    external: true